export enum ITEMSCATEGORY {
  KOTA = "KOTA",
  CHICKEN_DUST = "CHICKEN_DUST",
  INHLOKO = "INHLOKO",
  MOGUDO = "MOGUDO",
  FATCAKES = "FATCAKES",
  DAGWOOD = "DAGWOOD",
  SCONES = "SCONES",
  MUFFINS = "MUFFINS",
}
